import { readFileSync } from 'node:fs'
import { describe, it, expect } from 'vitest'
import {
  parseDdspModel,
  DdspDecoder,
  DdspModelBank,
  DdspKernel,
  renderHarmonicFrames,
  ddspNoiseFir,
  ddspCosBasis,
} from '../src/dsp/ddsp'
import type { DdspModel } from '../src/dsp/ddsp'
import { compileGraph } from '../src/compile'
import type { GraphSpec } from '../src/graph'
import type { DspContext } from '../src/dsp/types'
import { goertzel } from './util/goertzel'

/* Golden fixtures generated by training/ddsp/make_fixture.py from the PyTorch
 * reference. Every numeric claim in this file is pinned there; regenerate the
 * fixtures (and re-commit) only on a deliberate SPEC.md change. */
const fixtureBin = new Uint8Array(readFileSync(new URL('./fixtures/ddsp-fixture.bin', import.meta.url)))
interface Golden {
  frames: { f0_hz: number[]; loudness_db: number[] }
  intermediates: { mlp_concat: number[][]; gru_h: number[][] }
  outputs: { amp: number[]; harm_amps: number[][]; noise_mags: number[][] }
  harmonic_render: { sample_rate: number; hop: number; samples: number[] }
}
const golden = JSON.parse(
  readFileSync(new URL('./fixtures/ddsp-golden.json', import.meta.url), 'utf8'),
) as Golden

const close = (a: number, b: number, atol: number, rtol = 1e-3): boolean =>
  Math.abs(a - b) <= atol + rtol * Math.abs(b)

const closeAll = (a: ArrayLike<number>, b: number[], atol: number, rtol = 1e-3): void => {
  expect(a.length).toBe(b.length)
  for (let i = 0; i < b.length; i++) {
    if (!close(a[i]!, b[i]!, atol, rtol)) {
      expect.fail(`index ${i}: got ${a[i]}, want ${b[i]} (atol ${atol})`)
    }
  }
}

describe('parseDdspModel', () => {
  it('parses the fixture and exposes the header', () => {
    const m = parseDdspModel(fixtureBin)
    expect(m.header.name).toBe('fixture')
    expect(m.header.sampleRate).toBe(48000)
    expect(m.header.hop).toBe(64)
    expect(m.header.nHarmonics).toBe(8)
    expect(m.header.nNoise).toBe(9)
    expect(m.gruWih.length).toBe(3 * 5 * 12)
  })

  it('rejects bad magic', () => {
    const bad = fixtureBin.slice()
    bad[0] = 0x58
    expect(() => parseDdspModel(bad)).toThrow(/bad magic/)
  })

  it('rejects an unsupported version', () => {
    const bad = fixtureBin.slice()
    bad[4] = 99
    expect(() => parseDdspModel(bad)).toThrow(/version/)
  })

  it('rejects truncated tensor data', () => {
    expect(() => parseDdspModel(fixtureBin.slice(0, fixtureBin.length - 8))).toThrow(/out of range/)
  })

  it('reads out_norm when present, defaults to 1 (old files), clamps insanity', () => {
    expect(parseDdspModel(fixtureBin).header.outNorm).toBe(1) // fixture predates the field
    const rebuild = (mut: (h: Record<string, unknown>) => void): Uint8Array => {
      const dv = new DataView(fixtureBin.buffer, fixtureBin.byteOffset)
      const hlen = dv.getUint32(8, true)
      const header = JSON.parse(Buffer.from(fixtureBin.subarray(12, 12 + hlen)).toString('utf8'))
      mut(header)
      const hjson = Buffer.from(JSON.stringify(header), 'utf8')
      const dataStart = 12 + hlen + ((4 - ((12 + hlen) % 4)) % 4)
      const newDataStart = 12 + hjson.length + ((4 - ((12 + hjson.length) % 4)) % 4)
      const out = new Uint8Array(newDataStart + (fixtureBin.length - dataStart))
      out.set(fixtureBin.subarray(0, 8), 0)
      new DataView(out.buffer).setUint32(8, hjson.length, true)
      out.set(hjson, 12)
      out.set(fixtureBin.subarray(dataStart), newDataStart)
      return out
    }
    expect(parseDdspModel(rebuild((h) => { h.out_norm = 0.43 })).header.outNorm).toBe(0.43)
    expect(parseDdspModel(rebuild((h) => { h.out_norm = 9999 })).header.outNorm).toBe(20)
  })

  it('rejects an n_noise whose FIR length is not a power of two', () => {
    // rebuild the file with n_noise bumped 9 -> 10 (tensor shapes untouched:
    // the header check must fire before any tensor validation)
    const dv = new DataView(fixtureBin.buffer, fixtureBin.byteOffset)
    const hlen = dv.getUint32(8, true)
    const header = JSON.parse(Buffer.from(fixtureBin.subarray(12, 12 + hlen)).toString('utf8'))
    header.n_noise = 10
    const hjson = Buffer.from(JSON.stringify(header), 'utf8')
    const dataStart = 12 + hlen + ((4 - ((12 + hlen) % 4)) % 4)
    const newDataStart = 12 + hjson.length + ((4 - ((12 + hjson.length) % 4)) % 4)
    const out = new Uint8Array(newDataStart + (fixtureBin.length - dataStart))
    out.set(fixtureBin.subarray(0, 8), 0)
    new DataView(out.buffer).setUint32(8, hjson.length, true)
    out.set(hjson, 12)
    out.set(fixtureBin.subarray(dataStart), newDataStart)
    expect(() => parseDdspModel(out)).toThrow(/power of two/)
  })
})

describe('DdspDecoder golden parity with the PyTorch reference', () => {
  const model = parseDdspModel(fixtureBin)
  const T = golden.frames.f0_hz.length

  it('matches gru hidden state, amps and noise mags on every frame', () => {
    const dec = new DdspDecoder(model)
    for (let f = 0; f < T; f++) {
      dec.step(golden.frames.f0_hz[f]!, golden.frames.loudness_db[f]!)
      closeAll(dec.gruH, golden.intermediates.gru_h[f]!, 2e-4)
      closeAll(dec.harmAmps, golden.outputs.harm_amps[f]!, 5e-5)
      closeAll(dec.noiseMags, golden.outputs.noise_mags[f]!, 2e-4)
    }
  })

  it('reset() restores the initial state exactly', () => {
    const dec = new DdspDecoder(model)
    dec.step(golden.frames.f0_hz[0]!, golden.frames.loudness_db[0]!)
    const first = Array.from(dec.harmAmps)
    for (let f = 1; f < T; f++) dec.step(golden.frames.f0_hz[f]!, golden.frames.loudness_db[f]!)
    dec.reset()
    dec.step(golden.frames.f0_hz[0]!, golden.frames.loudness_db[0]!)
    expect(Array.from(dec.harmAmps)).toEqual(first)
  })
})

describe('harmonic renderer golden parity', () => {
  it('matches the PyTorch additive render sample-for-sample', () => {
    const f0 = Float32Array.from(golden.frames.f0_hz)
    const amps = golden.outputs.harm_amps.map((a) => Float32Array.from(a))
    const out = renderHarmonicFrames(f0, amps, golden.harmonic_render.sample_rate, golden.harmonic_render.hop)
    closeAll(out, golden.harmonic_render.samples, 2e-4, 0)
  })
})

describe('ddspNoiseFir keeps noise bands at their trained frequencies', () => {
  const J = 65
  const taps = 2 * (J - 1)
  const basis = ddspCosBasis(J)

  /** |DFT| of the FIR at engine band centers (bin b = b/taps cycles/sample). */
  const response = (fir: Float32Array): number[] => {
    const out: number[] = []
    for (let b = 0; b < J; b++) {
      let re = 0
      let im = 0
      for (let t = 0; t < taps; t++) {
        const ph = (2 * Math.PI * b * t) / taps
        re += fir[t]! * Math.cos(ph)
        im -= fir[t]! * Math.sin(ph)
      }
      out.push(Math.hypot(re, im))
    }
    return out
  }
  const argmax = (xs: number[]): number => xs.indexOf(Math.max(...xs))

  it('same rate: a band-32 magnitude peak stays at band 32', () => {
    const mags = new Float32Array(J).fill(1e-4)
    mags[32] = 1
    const fir = new Float32Array(taps)
    ddspNoiseFir(mags, 1, basis, fir)
    expect(argmax(response(fir))).toBe(32)
  })

  it('double-rate engine: the peak lands at band 16 (same absolute Hz)', () => {
    const mags = new Float32Array(J).fill(1e-4)
    mags[32] = 1
    const fir = new Float32Array(taps)
    ddspNoiseFir(mags, 2, basis, fir)
    expect(argmax(response(fir))).toBe(16)
  })

  it('bands above the model Nyquist are zeroed, not wrapped', () => {
    const mags = new Float32Array(J).fill(1)
    const fir = new Float32Array(taps)
    ddspNoiseFir(mags, 48000 / 22050, basis, fir) // model bandwidth ends at ~band 29.8
    const r = response(fir)
    const top = r.slice(40).reduce((a, b) => a + b, 0)
    const bottom = r.slice(0, 24).reduce((a, b) => a + b, 0)
    expect(top).toBeLessThan(bottom * 0.05)
  })
})

/* ------------------------------------------------------------------ kernel */

const model = parseDdspModel(fixtureBin)
const mkCtx = (): DspContext => {
  const bank = new DdspModelBank()
  bank.set('fixture', model)
  return { sampleRate: 48000, ddsp: bank }
}

interface Drive {
  gate?: (i: number) => number
  freq?: number | ((i: number) => number)
  vel?: number
  breath?: number
  vib?: number
  vibrate?: number
  air?: number
  bright?: number
  scoop?: number
  fall?: number
}

/** Run a kernel over n samples in `split`-sized chunks (default one block). */
const run = (k: DdspKernel, ctx: DspContext, n: number, d: Drive = {}, splits?: number[]): Float32Array => {
  const out = new Float32Array(n)
  const chunk = (from: number, len: number): void => {
    const mk = (fn: (i: number) => number): Float32Array => Float32Array.from({ length: len }, (_, j) => fn(from + j))
    const buf = out.subarray(from, from + len)
    k.process(
      len,
      {
        gate: mk(d.gate ?? (() => 1)),
        freq: mk(typeof d.freq === 'function' ? d.freq : () => (d.freq as number | undefined) ?? 220),
        vel: mk(() => d.vel ?? 1),
        breath: mk(() => d.breath ?? 0),
        vib: mk(() => d.vib ?? 0),
        vibrate: mk(() => d.vibrate ?? 5.5),
        air: mk(() => d.air ?? 1),
        bright: mk(() => d.bright ?? 0),
        scoop: mk(() => d.scoop ?? 0),
        fall: mk(() => d.fall ?? 0),
      },
      buf,
      ctx,
    )
  }
  let at = 0
  const plan = splits ?? []
  for (const s of plan) {
    chunk(at, s)
    at += s
  }
  while (at < n) {
    const len = Math.min(128, n - at)
    chunk(at, len)
    at += len
  }
  return out
}

const rms = (x: Float32Array, from = 0, to = x.length): number => {
  let s = 0
  for (let i = from; i < to; i++) s += x[i]! * x[i]!
  return Math.sqrt(s / (to - from))
}

describe('DdspKernel', () => {
  const sr = 48000

  it('is silent without a model, then audible once the bank has it (live load)', () => {
    const bank = new DdspModelBank()
    const ctx: DspContext = { sampleRate: sr, ddsp: bank }
    const k = new DdspKernel({ model: 'fixture' })
    expect(rms(run(k, ctx, 4096))).toBe(0)
    bank.set('fixture', model)
    expect(rms(run(k, ctx, 4096))).toBeGreaterThan(1e-4)
  })

  it('renders finite, bounded audio while gated (unity makeup)', () => {
    const k = new DdspKernel({ model: 'fixture', gain: 1 })
    const out = run(k, mkCtx(), sr)
    let peak = 0
    for (const v of out) {
      expect(Number.isFinite(v)).toBe(true)
      peak = Math.max(peak, Math.abs(v))
    }
    expect(peak).toBeGreaterThan(1e-5)
    expect(peak).toBeLessThan(4) // exp_sigmoid caps model-scale output near 2
  })

  it('gain is linear output makeup and defaults to 2', () => {
    const unity = run(new DdspKernel({ model: 'fixture', gain: 1 }), mkCtx(), 8192)
    const dflt = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 8192)
    for (let i = 4000; i < 4032; i++) {
      expect(dflt[i]!).toBeCloseTo(unity[i]! * 2, 4)
    }
  })

  it('decays to silence after the gate drops', () => {
    const k = new DdspKernel({ model: 'fixture', release: 0.05 })
    const out = run(k, mkCtx(), sr, { gate: (i) => (i < sr / 4 ? 1 : 0) })
    expect(rms(out, 0, sr / 4)).toBeGreaterThan(1e-4)
    expect(rms(out, (7 * sr) / 8, sr)).toBeLessThan(1e-5)
  })

  it('velocity reaches the decoder: different vel produces different audio', () => {
    // The fixture's weights are random, so loudness-in -> amplitude-out is not
    // monotonic here (that property belongs to trained-model verification);
    // what THIS pins is that vel actually conditions the decoder.
    const loud = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { vel: 1 })
    const soft = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { vel: 0.2 })
    let diff = 0
    for (let i = sr / 4; i < sr / 2; i++) diff = Math.max(diff, Math.abs(loud[i]! - soft[i]!))
    expect(diff).toBeGreaterThan(1e-3)
  })

  it('is deterministic: fresh kernel and reset() both reproduce sample-for-sample', () => {
    const a = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 8192)
    const b = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 8192)
    expect(a).toEqual(b)
    const k = new DdspKernel({ model: 'fixture' })
    const ctx = mkCtx()
    const first = run(k, ctx, 8192)
    k.reset()
    expect(run(k, ctx, 8192)).toEqual(first)
  })

  it('is block-split invariant (event-boundary splits cannot change the audio)', () => {
    const whole = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 1024)
    const split = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 1024, {}, [37, 91, 1, 127, 64])
    expect(split).toEqual(whole)
    // ...including with the whole articulation set active
    const art: Drive = { vib: 0.4, air: 1.8, bright: 1.2, scoop: 3, fall: 5, gate: (i) => (i < 600 ? 1 : 0) }
    const wholeArt = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 1024, art)
    const splitArt = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 1024, art, [53, 11, 127, 1, 99])
    expect(splitArt).toEqual(wholeArt)
  })

  it('air scales the noise half: more air, more energy; zero air, less', () => {
    const dry = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { air: 0 })
    const norm = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { air: 1 })
    const airy = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { air: 3 })
    const tail = [sr / 4, sr / 2] as const
    expect(rms(dry, ...tail)).toBeLessThan(rms(norm, ...tail))
    expect(rms(norm, ...tail)).toBeLessThan(rms(airy, ...tail))
  })

  it('bright tilts the spectrum while roughly preserving level', () => {
    const dark = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { bright: -2, air: 0 })
    const brt = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { bright: 2, air: 0 })
    // spectral centroid proxy: high-harmonic power over fundamental power
    const seg = (x: Float32Array): Float32Array => x.subarray(sr / 4, sr / 2)
    const ratio = (x: Float32Array): number =>
      (goertzel(seg(x), 220 * 6, sr) + goertzel(seg(x), 220 * 7, sr)) / (goertzel(seg(x), 220, sr) + 1e-12)
    expect(ratio(brt)).toBeGreaterThan(ratio(dark) * 3)
    // loudness-preserving: levels stay within ~6 dB of each other
    const dbDiff = 20 * Math.log10((rms(brt, sr / 4, sr / 2) + 1e-12) / (rms(dark, sr / 4, sr / 2) + 1e-12))
    expect(Math.abs(dbDiff)).toBeLessThan(6)
  })

  it('scoop starts the note below pitch and arrives at it', () => {
    const straight = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { air: 0 })
    const scooped = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr / 2, { air: 0, scoop: 4 })
    // during the first 60 ms the scooped note has less energy AT the target
    // pitch than the straight one; by the second half they match
    const early = (x: Float32Array): number => goertzel(x.subarray(480, Math.round(0.06 * sr)), 220, sr)
    expect(early(scooped)).toBeLessThan(early(straight) * 0.5)
    const late = (x: Float32Array): number => goertzel(x.subarray(sr / 4, sr / 2), 220, sr)
    expect(late(scooped)).toBeGreaterThan(late(straight) * 0.5)
  })

  it('legato: a mid-gate pitch step never re-attacks, clicks or gaps, and FLOWS', () => {
    // true legato is a finger change: pitch steps 220 -> 330 in one sample
    // while the gate stays high. With flow (default), the voice follows a
    // ~28 ms in-distribution transition — too short to hear as a slide, long
    // enough that the decoder produces the note-change sound it learned.
    const step = (i: number): number => (i < sr / 3 ? 220 : 330)
    const k = new DdspKernel({ model: 'fixture', punch: 12 })
    const out = run(k, mkCtx(), (2 * sr) / 3, { freq: step, air: 0 })
    let maxStep = 0
    let maxAmp = 0
    for (let i = sr / 8; i < (2 * sr) / 3; i++) {
      maxStep = Math.max(maxStep, Math.abs(out[i]! - out[i - 1]!))
      maxAmp = Math.max(maxAmp, Math.abs(out[i]!))
    }
    expect(maxStep).toBeLessThan(maxAmp * 0.3) // no click at the boundary
    // no gap: the boundary keeps sounding through the flow dip (-3.5 dB)
    const border = rms(out, Math.round(sr / 3) - 512, Math.round(sr / 3) + 512)
    const steady = rms(out, sr / 6, sr / 4)
    expect(border).toBeGreaterThan(steady * 0.4)
    // by 80 ms the new note dominates the audio (long window — spectrally
    // resolvable, unlike the transition itself)
    const settled = out.subarray(Math.round(sr / 3 + 0.08 * sr), Math.round(sr / 3 + 0.18 * sr))
    expect(goertzel(settled, 330, sr)).toBeGreaterThan(goertzel(settled, 220, sr) * 2)
  })

  it('flow: the RENDERED pitch snaps like a finger change (~8 ms, no smear)', () => {
    // Rendered pitch must arrive fast — slower transitions read as
    // portamento on fast passages (they did, at 28-56 ms). The decoder's
    // conditioning keeps its own slower curve internally; what the ear
    // tracks is this trajectory.
    const k = new DdspKernel({ model: 'fixture' })
    const ctx = mkCtx()
    const at = (ms: number): number => Math.round((ms / 1000) * sr)
    const boundary = 4096
    const f0At: Record<number, number> = {}
    const marks = [boundary - 1, boundary + at(3), boundary + at(15), boundary + at(30), boundary + at(70)]
    let done = 0
    const total = boundary + at(100)
    const out = new Float32Array(128)
    for (let i = 0; i < total; i += 128) {
      const len = Math.min(128, total - i)
      const mk = (v: (j: number) => number): Float32Array => Float32Array.from({ length: len }, (_, j) => v(i + j))
      k.process(len, {
        gate: mk(() => 1), freq: mk((j) => (j < boundary ? 220 : 330)), vel: mk(() => 1),
        breath: mk(() => 0), vib: mk(() => 0), vibrate: mk(() => 5.5),
        air: mk(() => 1), bright: mk(() => 0), scoop: mk(() => 0), fall: mk(() => 0),
      }, out.subarray(0, len), ctx)
      while (done < marks.length && marks[done]! < i + len) {
        f0At[marks[done]!] = k.currentF0()
        done++
      }
    }
    expect(f0At[boundary - 1]!).toBeCloseTo(220, 0)
    // 3 ms in: mid-flight (continuous, so no click) — by 15 ms: ARRIVED
    expect(f0At[boundary + at(3)]!).toBeGreaterThan(225)
    expect(f0At[boundary + at(3)]!).toBeLessThan(325)
    expect(f0At[boundary + at(15)]!).toBeCloseTo(330, 0)
    expect(f0At[boundary + at(30)]!).toBeCloseTo(330, 0)
    expect(f0At[boundary + at(70)]!).toBeCloseTo(330, 0)
  })

  it('flow: 0 disables the transition — the step lands within one decoder hop', () => {
    const step = (i: number): number => (i < sr / 3 ? 220 : 330)
    const k = new DdspKernel({ model: 'fixture', flow: 0 })
    const out = run(k, mkCtx(), (2 * sr) / 3, { freq: step, air: 0 })
    const after = out.subarray(Math.round(sr / 3 + 0.015 * sr), Math.round(sr / 3 + 0.08 * sr))
    expect(goertzel(after, 330, sr)).toBeGreaterThan(goertzel(after, 220, sr) * 2)
    for (const v of out) expect(Number.isFinite(v)).toBe(true)
  })

  it('portamento (a separate thing from legato): a mid-gate pitch glide never re-attacks or clicks', () => {
    // one "bow": gate high throughout, freq slides 220 -> 330 over the middle
    const glide = (i: number): number => {
      if (i < sr / 4) return 220
      if (i > sr / 2) return 330
      return 220 + (110 * (i - sr / 4)) / (sr / 4)
    }
    const k = new DdspKernel({ model: 'fixture', punch: 12 })
    const out = run(k, mkCtx(), (3 * sr) / 4, { freq: glide, air: 0 })
    // no re-attack: the punch accent only fires at the ONE gate edge, so the
    // glide region's envelope stays continuous — no sample-to-sample jump
    // bigger than the waveform's own slope anywhere after the attack settles
    let maxStep = 0
    for (let i = sr / 8; i < (3 * sr) / 4; i++) maxStep = Math.max(maxStep, Math.abs(out[i]! - out[i - 1]!))
    let maxAmp = 0
    for (let i = sr / 8; i < (3 * sr) / 4; i++) maxAmp = Math.max(maxAmp, Math.abs(out[i]!))
    // a 330 Hz partial stack moves at most ~2*pi*f_max/sr of its amplitude per
    // sample; a click would be an order of magnitude above this bound
    expect(maxStep).toBeLessThan(maxAmp * 0.3)
    // and the glide actually lands: end of render is pitched at 330, not 220
    const tail = out.subarray(Math.round(0.6 * sr), Math.round(0.75 * sr))
    expect(goertzel(tail, 330, sr)).toBeGreaterThan(goertzel(tail, 220, sr) * 3)
  })

  it('punch, fall and vibdelay all reach the audio', () => {
    const gate: Drive['gate'] = (i) => (i < 8000 ? 1 : 0)
    const base = run(new DdspKernel({ model: 'fixture', punch: 0 }), mkCtx(), 16384, { gate })
    const punched = run(new DdspKernel({ model: 'fixture', punch: 8 }), mkCtx(), 16384, { gate })
    const fallen = run(new DdspKernel({ model: 'fixture', punch: 0 }), mkCtx(), 16384, { gate, fall: 7 })
    const maxDiff = (a: Float32Array, b: Float32Array): number => {
      let m = 0
      for (let i = 0; i < a.length; i++) m = Math.max(m, Math.abs(a[i]! - b[i]!))
      return m
    }
    expect(maxDiff(base, punched)).toBeGreaterThan(1e-4)
    expect(maxDiff(base, fallen)).toBeGreaterThan(1e-4)
    const slowVib = run(new DdspKernel({ model: 'fixture', vibdelay: 2 }), mkCtx(), 16384, { gate, vib: 0.5 })
    const fastVib = run(new DdspKernel({ model: 'fixture', vibdelay: 0.05 }), mkCtx(), 16384, { gate, vib: 0.5 })
    expect(maxDiff(slowVib, fastVib)).toBeGreaterThan(1e-4)
  })

  it('survives NaN/zero freq without emitting NaN', () => {
    const k = new DdspKernel({ model: 'fixture' })
    const out = run(k, mkCtx(), 2048, { freq: NaN })
    for (const v of out) expect(Number.isFinite(v)).toBe(true)
    const out2 = run(new DdspKernel({ model: 'fixture' }), mkCtx(), 2048, { freq: 0 })
    for (const v of out2) expect(Number.isFinite(v)).toBe(true)
  })

  it('vibrato modulates pitch (output differs from the unmodulated render)', () => {
    const flat = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr, { vib: 0 })
    const wob = run(new DdspKernel({ model: 'fixture' }), mkCtx(), sr, { vib: 0.5 })
    let diff = 0
    for (let i = (3 * sr) / 4; i < sr; i++) diff = Math.max(diff, Math.abs(flat[i]! - wob[i]!))
    expect(diff).toBeGreaterThan(1e-4)
  })

  it('compiles as a graph node', () => {
    const spec: GraphSpec = {
      nodes: [
        { id: 0, type: 'gate', inputs: {} },
        { id: 1, type: 'notefreq', inputs: {} },
        { id: 2, type: 'ddsp', inputs: { gate: { node: 0 }, freq: { node: 1 } }, config: { model: 'fixture' } },
        { id: 3, type: 'out', inputs: { in: { node: 2 } } },
      ],
      out: 3,
      params: [],
    }
    const g = compileGraph(spec, mkCtx())
    expect(g.steps.some((s) => s.id === 2)).toBe(true)
  })
})

describe('DdspKernel output calibration and noise floor', () => {
  it('out_norm scales the voice linearly', () => {
    const loudModel = { ...model, header: { ...model.header, outNorm: 0.25 } }
    const bank = new DdspModelBank()
    bank.set('fixture', loudModel)
    const scaled = run(new DdspKernel({ model: 'fixture', gain: 1 }), { sampleRate: 48000, ddsp: bank }, 8192)
    const plain = run(new DdspKernel({ model: 'fixture', gain: 1 }), mkCtx(), 8192)
    for (let i = 4000; i < 4032; i++) expect(scaled[i]!).toBeCloseTo(plain[i]! * 0.25, 5)
  })

  it('the noise floor gate silences a noise-heavy model after release', () => {
    // a model whose noise head reproduces the recording's room floor: without
    // the gate the release would hiss at the floor level indefinitely
    const noisy = syntheticModel(64, 2, 96, 32, 33)
    noisy.noiseB.fill(2.5) // expSigmoid(2.5) ~ 1.6 per band — a LOUD floor
    const bank = new DdspModelBank()
    bank.set('noisy', noisy)
    const ctx: DspContext = { sampleRate: 48000, ddsp: bank }
    const k = new DdspKernel({ model: 'noisy', release: 0.05, gain: 1 })
    const sr = 48000
    const out = run(k, ctx, sr, { gate: (i) => (i < sr / 4 ? 1 : 0) })
    expect(rms(out, 0, sr / 4)).toBeGreaterThan(1e-3) // it does sound
    expect(rms(out, (7 * sr) / 8, sr)).toBeLessThan(1e-5) // and truly stops
  })
})

describe('tempo-adaptive articulation', () => {
  const sr = 48000
  /** Drive duty-cycled detache notes one sample at a time and read the
   *  envelope 33 ms after note 4's gate-off. The fixture's random weights
   *  make audio amplitude non-monotonic in loudness, so the release
   *  behavior is asserted on the envelope itself. */
  const envAfterGap = (ioiMs: number): number => {
    const ioi = Math.round((ioiMs / 1000) * sr)
    const k = new DdspKernel({ model: 'fixture' })
    const ctx = mkCtx()
    const readAt = ioi * 4 + Math.round(ioi * 0.7) + Math.round(0.033 * sr)
    const out = new Float32Array(1)
    const one = (v: number): Float32Array => Float32Array.from([v])
    for (let i = 0; i <= readAt; i++) {
      k.process(1, {
        gate: one(i % ioi < ioi * 0.7 ? 1 : 0), freq: one(220), vel: one(1),
        breath: one(0), vib: one(0), vibrate: one(5.5), air: one(0),
        bright: one(0), scoop: one(0), fall: one(0),
      }, out, ctx)
    }
    return k.currentLoudness()
  }

  it('release scales with note rate: fast gaps notch, slow phrases ring', () => {
    // same 33 ms after gate-off in both cases — only the note RATE differs
    const fast = envAfterGap(110) // ~136 bpm sixteenths
    const slow = envAfterGap(600)
    expect(fast).toBeLessThan(slow - 8) // fast release cuts far deeper, same elapsed time
    expect(fast).toBeLessThan(-30) // a real notch, not a smear
  })

  it('fast notes still speak: early level reaches the note body quickly', () => {
    const ioi = Math.round(0.11 * sr)
    const k = new DdspKernel({ model: 'fixture' })
    const out = run(k, mkCtx(), ioi * 6, { gate: (i) => (i % ioi < ioi * 0.7 ? 1 : 0), air: 0 })
    const on4 = ioi * 4
    const early = rms(out, on4, on4 + Math.round(0.025 * sr))
    const mid = rms(out, on4 + Math.round(ioi * 0.3), on4 + Math.round(ioi * 0.55))
    expect(early / (mid + 1e-12)).toBeGreaterThan(0.55)
  })
})

describe('onset texture', () => {
  it('the onset noise boost is real: scratch on vs off at the same window', () => {
    const sr = 48000
    // identical drive; only flow (which scales the scratch) differs. The
    // fixture's random loudness->spectrum map makes early-vs-late
    // comparisons meaningless, so compare the SAME early window instead.
    const on = run(new DdspKernel({ model: 'fixture', attack: 0.01 }), mkCtx(), sr, { air: 1 })
    const off = run(new DdspKernel({ model: 'fixture', attack: 0.01, flow: 0 }), mkCtx(), sr, { air: 1 })
    const w = Math.round(0.04 * sr)
    const from = Math.round(0.004 * sr)
    // 301 Hz sits between the fundamental and 2nd harmonic: noise-dominated
    const noiseOn = goertzel(on.subarray(from, from + w), 301, sr)
    const noiseOff = goertzel(off.subarray(from, from + w), 301, sr)
    expect(noiseOn).toBeGreaterThan(noiseOff * 1.8)
    // and the boost is gone by half a second (same comparison, late window)
    const lateFrom = Math.round(0.5 * sr)
    const lateOn = goertzel(on.subarray(lateFrom, lateFrom + w), 301, sr)
    const lateOff = goertzel(off.subarray(lateFrom, lateFrom + w), 301, sr)
    expect(lateOn).toBeLessThan(lateOff * 1.5)
    expect(lateOn).toBeGreaterThan(lateOff * 0.5)
  })
})

describe('DdspKernel perf sanity', () => {
  it('8 voices render faster than real time by a wide margin', () => {
    // Full-size architecture (H=128 L=3 G=192 K=64 J=65) with synthetic
    // weights: the shipped models' exact shape, so this catches a
    // catastrophic perf regression without depending on trained weights.
    const big = syntheticModel(128, 3, 192, 64, 65)
    const bank = new DdspModelBank()
    bank.set('big', big)
    const ctx: DspContext = { sampleRate: 48000, ddsp: bank }
    const kernels = Array.from({ length: 8 }, () => new DdspKernel({ model: 'big' }))
    const seconds = 0.5
    const t0 = performance.now()
    for (const k of kernels) run(k, ctx, 48000 * seconds)
    const wall = (performance.now() - t0) / 1000
    // generous bound (2x realtime for ALL 8 voices) to stay CI-stable; the
    // real budget check lives in scripts/measure-audio-style profiling
    expect(wall).toBeLessThan(seconds * 2 * 8)
  })
})

/** Random full-size model built directly (no .bin) for perf testing. */
function syntheticModel(H: number, L: number, G: number, K: number, J: number): DdspModel {
  let s = 123456789
  const rand = (): number => {
    s ^= s << 13
    s ^= s >>> 17
    s ^= s << 5
    s >>>= 0
    return (s / 0x100000000 - 0.5) * 0.4
  }
  const arr = (n: number): Float32Array => Float32Array.from({ length: n }, rand)
  const ones = (n: number): Float32Array => new Float32Array(n).fill(1)
  const mlp = (inN: number): DdspModel['inMlpF0'] =>
    Array.from({ length: L }, (_, l) => ({
      w: arr(H * (l === 0 ? inN : H)),
      b: arr(H),
      lnG: ones(H),
      lnB: arr(H),
      inN: l === 0 ? inN : H,
      outN: H,
    }))
  return {
    header: {
      name: 'big', license: 'CC0-1.0', provenance: 'synthetic', sampleRate: 48000,
      hop: 512, nHarmonics: K, nNoise: J, hidden: H, layers: L, gru: G, outNorm: 1,
    },
    inMlpF0: mlp(1),
    inMlpLd: mlp(1),
    outMlp: mlp(G + 2),
    gruWih: arr(3 * G * 2 * H),
    gruWhh: arr(3 * G * G),
    gruBih: arr(3 * G),
    gruBhh: arr(3 * G),
    harmW: arr((1 + K) * H),
    harmB: arr(1 + K),
    noiseW: arr(J * H),
    noiseB: arr(J),
  }
}
