/** DDSP instrument synth: a small trained decoder (MLPs + GRU) runs at frame
 *  rate (~94 Hz) and emits harmonic amplitudes + noise-filter magnitudes; a
 *  deterministic additive + filtered-noise renderer runs per sample. The
 *  weight format and every numeric detail here are pinned to the PyTorch
 *  reference by training/ddsp/SPEC.md and the golden vectors in
 *  test/fixtures/ (regenerated by training/ddsp/make_fixture.py). */

import type { DspContext, Kernel } from './types'
import { flush } from './util'

/* ------------------------------------------------------------------ format */

export interface DdspHeader {
  name: string
  license: string
  provenance: string
  sampleRate: number
  hop: number
  nHarmonics: number
  nNoise: number
  hidden: number
  layers: number
  gru: number
  /** per-model output calibration written at export: maps this model's forte
   *  level onto the shared reference the default gain expects (absent in old
   *  files = 1). Without it a model trained on a hot recording clips. */
  outNorm: number
}

interface MlpLayer {
  w: Float32Array // [out, in] row-major (torch Linear layout)
  b: Float32Array
  lnG: Float32Array // LayerNorm gamma
  lnB: Float32Array // LayerNorm beta
  inN: number
  outN: number
}

export interface DdspModel {
  header: DdspHeader
  inMlpF0: MlpLayer[]
  inMlpLd: MlpLayer[]
  outMlp: MlpLayer[]
  gruWih: Float32Array // [3G, 2H] rows ordered r, z, n (torch layout)
  gruWhh: Float32Array // [3G, G]
  gruBih: Float32Array
  gruBhh: Float32Array
  harmW: Float32Array // [1 + K, H]
  harmB: Float32Array
  noiseW: Float32Array // [J, H]
  noiseB: Float32Array
}

const MAGIC = 0x50534452 // 'RDSP' little-endian

function halfToFloat(h: number): number {
  const s = h & 0x8000 ? -1 : 1
  const e = (h >> 10) & 0x1f
  const m = h & 0x3ff
  if (e === 0) return s * m * 2 ** -24
  if (e === 31) return m ? NaN : s * Infinity
  return s * (m + 1024) * 2 ** (e - 25)
}

function intField(h: Record<string, unknown>, key: string, min: number, max: number): number {
  const v = h[key]
  if (typeof v !== 'number' || !Number.isInteger(v) || v < min || v > max) {
    throw new Error(`ddsp model header '${key}' must be an integer in [${min}, ${max}]`)
  }
  return v
}

function strField(h: Record<string, unknown>, key: string): string {
  const v = h[key]
  return typeof v === 'string' ? v : ''
}

/** UTF-8 decode without TextDecoder (not guaranteed in AudioWorkletGlobalScope). */
function utf8Decode(bytes: Uint8Array): string {
  let out = ''
  let i = 0
  while (i < bytes.length) {
    const b0 = bytes[i++]!
    let cp: number
    if (b0 < 0x80) cp = b0
    else if (b0 < 0xe0) cp = ((b0 & 0x1f) << 6) | (bytes[i++]! & 0x3f)
    else if (b0 < 0xf0) cp = ((b0 & 0x0f) << 12) | ((bytes[i++]! & 0x3f) << 6) | (bytes[i++]! & 0x3f)
    else cp = ((b0 & 0x07) << 18) | ((bytes[i++]! & 0x3f) << 12) | ((bytes[i++]! & 0x3f) << 6) | (bytes[i++]! & 0x3f)
    out += String.fromCodePoint(cp)
  }
  return out
}

/** Parse an RDSP .bin (SPEC.md). Validates the header ranges and that every
 *  tensor the architecture requires is present with the expected shape, so a
 *  malformed file fails HERE (control plane) and never on the audio path. */
export function parseDdspModel(bytes: Uint8Array): DdspModel {
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  if (bytes.byteLength < 12 || dv.getUint32(0, true) !== MAGIC) {
    throw new Error('not a ddsp model (bad magic)')
  }
  const version = dv.getUint32(4, true)
  if (version !== 1) throw new Error(`unsupported ddsp model version ${version}`)
  const hlen = dv.getUint32(8, true)
  if (12 + hlen > bytes.byteLength) throw new Error('ddsp model header truncated')
  let raw: unknown
  try {
    raw = JSON.parse(utf8Decode(bytes.subarray(12, 12 + hlen)))
  } catch {
    throw new Error('ddsp model header is not valid JSON')
  }
  if (typeof raw !== 'object' || raw === null) throw new Error('ddsp model header is not an object')
  const h = raw as Record<string, unknown>
  const header: DdspHeader = {
    name: strField(h, 'name'),
    license: strField(h, 'license'),
    provenance: strField(h, 'provenance'),
    sampleRate: intField(h, 'sample_rate', 8000, 192000),
    hop: intField(h, 'hop', 32, 8192),
    nHarmonics: intField(h, 'n_harmonics', 1, 256),
    nNoise: intField(h, 'n_noise', 3, 513),
    hidden: intField(h, 'hidden', 1, 1024),
    layers: intField(h, 'layers', 1, 8),
    gru: intField(h, 'gru', 1, 1024),
    outNorm:
      typeof h['out_norm'] === 'number' && Number.isFinite(h['out_norm'])
        ? clampNum(h['out_norm'] as number, 0.05, 20)
        : 1,
  }
  // The noise ring buffer indexes with a mask, so the FIR length 2*(n_noise-1)
  // must be a power of two: n_noise is 2^m + 1 (65, 33, 9, ...).
  const taps = header.nNoise - 1
  if ((taps & (taps - 1)) !== 0) {
    throw new Error(`ddsp model 'n_noise' must be a power of two plus one, got ${header.nNoise}`)
  }
  const specs = h['tensors']
  if (!Array.isArray(specs)) throw new Error(`ddsp model header 'tensors' must be an array`)
  const dataStart = 12 + hlen + ((4 - ((12 + hlen) % 4)) % 4)
  const byName = new Map<string, Float32Array>()
  for (const s of specs as unknown[]) {
    if (typeof s !== 'object' || s === null) throw new Error('ddsp tensor spec must be an object')
    const spec = s as Record<string, unknown>
    const name = spec['name']
    const shape = spec['shape']
    const offset = spec['offset']
    if (typeof name !== 'string' || !Array.isArray(shape) || typeof offset !== 'number' || !Number.isInteger(offset)) {
      throw new Error('ddsp tensor spec needs string name, array shape, integer offset')
    }
    let count = 1
    for (const d of shape) {
      if (typeof d !== 'number' || !Number.isInteger(d) || d < 1 || d > 65536) {
        throw new Error(`ddsp tensor '${name}' has a bad shape`)
      }
      count *= d
    }
    const start = dataStart + offset
    if (offset < 0 || count > 1 << 24 || start + count * 2 > bytes.byteLength) {
      throw new Error(`ddsp tensor '${name}' data out of range`)
    }
    const out = new Float32Array(count)
    for (let i = 0; i < count; i++) {
      out[i] = halfToFloat(dv.getUint16(start + i * 2, true))
    }
    byName.set(name, out)
  }
  const take = (name: string, len: number): Float32Array => {
    const t = byName.get(name)
    if (!t) throw new Error(`ddsp model missing tensor '${name}'`)
    if (t.length !== len) throw new Error(`ddsp tensor '${name}' has ${t.length} values, expected ${len}`)
    return t
  }
  const H = header.hidden
  const G = header.gru
  const mlp = (prefix: string, inN: number): MlpLayer[] => {
    const out: MlpLayer[] = []
    for (let l = 0; l < header.layers; l++) {
      const nin = l === 0 ? inN : H
      out.push({
        w: take(`${prefix}.${l * 3}.weight`, H * nin),
        b: take(`${prefix}.${l * 3}.bias`, H),
        lnG: take(`${prefix}.${l * 3 + 1}.weight`, H),
        lnB: take(`${prefix}.${l * 3 + 1}.bias`, H),
        inN: nin,
        outN: H,
      })
    }
    return out
  }
  return {
    header,
    inMlpF0: mlp('in_mlp_f0', 1),
    inMlpLd: mlp('in_mlp_ld', 1),
    outMlp: mlp('out_mlp', G + 2),
    gruWih: take('gru.weight_ih_l0', 3 * G * 2 * H),
    gruWhh: take('gru.weight_hh_l0', 3 * G * G),
    gruBih: take('gru.bias_ih_l0', 3 * G),
    gruBhh: take('gru.bias_hh_l0', 3 * G),
    harmW: take('harm_head.weight', (1 + header.nHarmonics) * H),
    harmB: take('harm_head.bias', 1 + header.nHarmonics),
    noiseW: take('noise_head.weight', header.nNoise * H),
    noiseB: take('noise_head.bias', header.nNoise),
  }
}

/** parseDdspModel with a per-buffer memo: offline renders parse each model
 *  once per process, not once per stem (renderMix calls renderOffline per
 *  synth, and a parse is ~400k half->float conversions). */
const parsedCache = new WeakMap<Uint8Array, DdspModel>()
export function parseDdspModelCached(bytes: Uint8Array): DdspModel {
  let m = parsedCache.get(bytes)
  if (m === undefined) {
    m = parseDdspModel(bytes)
    parsedCache.set(bytes, m)
  }
  return m
}

/** Shared name -> model store, same adopt-or-publish contract as SampleBank:
 *  the engine fills it from loadDdspModel messages and kernels re-resolve per
 *  block, so a model loaded after compile becomes audible with no rebuild. */
export class DdspModelBank {
  private readonly map = new Map<string, DdspModel>()
  set(name: string, model: DdspModel): void {
    this.map.set(name, model)
  }
  delete(name: string): void {
    this.map.delete(name)
  }
  get(name: string): DdspModel | undefined {
    return this.map.get(name)
  }
  names(): string[] {
    return [...this.map.keys()]
  }
}

/* ----------------------------------------------------------------- decoder */

function expSigmoid(x: number): number {
  return 2.0 * Math.pow(1 / (1 + Math.exp(-x)), Math.LN10) + 1e-7
}

export function scaleF0(f0Hz: number): number {
  const f = f0Hz < 1e-5 ? 1e-5 : f0Hz
  return (69 + 12 * Math.log2(f / 440)) / 127
}

export function scaleLoudness(db: number): number {
  const d = db < -90 ? -90 : db > 0 ? 0 : db
  return (d + 90) / 90
}

function matvec(w: Float32Array, x: Float32Array, b: Float32Array, inN: number, outN: number, y: Float32Array): void {
  for (let o = 0; o < outN; o++) {
    let acc = b[o]!
    const row = o * inN
    for (let i = 0; i < inN; i++) acc += w[row + i]! * x[i]!
    y[o] = acc
  }
}

function layerNormLeaky(y: Float32Array, n: number, g: Float32Array, b: Float32Array): void {
  let mean = 0
  for (let i = 0; i < n; i++) mean += y[i]!
  mean /= n
  let variance = 0
  for (let i = 0; i < n; i++) {
    const d = y[i]! - mean
    variance += d * d
  }
  variance /= n
  const inv = 1 / Math.sqrt(variance + 1e-5)
  for (let i = 0; i < n; i++) {
    let v = (y[i]! - mean) * inv * g[i]! + b[i]!
    if (v < 0) v *= 0.2 // LeakyReLU(0.2)
    y[i] = v
  }
}

/** One per voice. step() advances the GRU one frame and refreshes harmAmps /
 *  noiseMags. All buffers preallocated; nothing allocates after construction.
 *  gru_h is exposed for the golden parity test only. */
export class DdspDecoder {
  readonly harmAmps: Float32Array
  readonly noiseMags: Float32Array
  readonly gruH: Float32Array
  private readonly m: DdspModel
  private readonly x: Float32Array // concat of the two input MLP outputs, 2H
  private readonly scalarIn: Float32Array
  private readonly mlpTmp: Float32Array
  private readonly mlpOut: Float32Array
  private readonly gates: Float32Array // 3G: r, z, n pre-activations, then h'
  private readonly outIn: Float32Array // G + 2
  private readonly y: Float32Array
  private readonly harm: Float32Array // 1 + K

  constructor(model: DdspModel) {
    const { hidden: H, gru: G, nHarmonics, nNoise } = model.header
    this.m = model
    this.harmAmps = new Float32Array(nHarmonics)
    this.noiseMags = new Float32Array(nNoise)
    this.gruH = new Float32Array(G)
    this.x = new Float32Array(2 * H)
    this.scalarIn = new Float32Array(1)
    this.mlpTmp = new Float32Array(H)
    this.mlpOut = new Float32Array(H)
    this.gates = new Float32Array(3 * G)
    this.outIn = new Float32Array(G + 2)
    this.y = new Float32Array(H)
    this.harm = new Float32Array(1 + nHarmonics)
  }

  reset(): void {
    this.gruH.fill(0)
    this.harmAmps.fill(0)
    this.noiseMags.fill(0)
  }

  /** src and dst must differ; layers > 1 ping-pong through mlpTmp so a layer
   *  never reads the buffer it is writing. */
  private mlp(layersArr: MlpLayer[], x0: Float32Array, out: Float32Array): void {
    let src = x0
    for (const l of layersArr) {
      matvec(l.w, src, l.b, l.inN, l.outN, this.mlpTmp)
      layerNormLeaky(this.mlpTmp, l.outN, l.lnG, l.lnB)
      out.set(this.mlpTmp.subarray(0, l.outN))
      src = out
    }
  }

  step(f0Hz: number, loudnessDb: number): void {
    const m = this.m
    const H = m.header.hidden
    const G = m.header.gru
    const f0s = scaleF0(f0Hz)
    const lds = scaleLoudness(loudnessDb)
    this.scalarIn[0] = f0s
    this.mlp(m.inMlpF0, this.scalarIn, this.mlpOut)
    this.x.set(this.mlpOut.subarray(0, H), 0)
    this.scalarIn[0] = lds
    this.mlp(m.inMlpLd, this.scalarIn, this.mlpOut)
    this.x.set(this.mlpOut.subarray(0, H), H)
    // GRU (torch semantics: separate input/hidden biases, gate order r, z, n)
    const gates = this.gates
    const inN = 2 * H
    for (let o = 0; o < 3 * G; o++) {
      let acc = m.gruBih[o]!
      const row = o * inN
      for (let i = 0; i < inN; i++) acc += m.gruWih[row + i]! * this.x[i]!
      gates[o] = acc
    }
    const h = this.gruH
    for (let o = 0; o < G; o++) {
      let hr = m.gruBhh[o]!
      let hz = m.gruBhh[G + o]!
      let hn = m.gruBhh[2 * G + o]!
      const rowR = o * G
      const rowZ = (G + o) * G
      const rowN = (2 * G + o) * G
      for (let i = 0; i < G; i++) {
        const hi = h[i]!
        hr += m.gruWhh[rowR + i]! * hi
        hz += m.gruWhh[rowZ + i]! * hi
        hn += m.gruWhh[rowN + i]! * hi
      }
      const r = 1 / (1 + Math.exp(-(gates[o]! + hr)))
      const z = 1 / (1 + Math.exp(-(gates[G + o]! + hz)))
      const nn = Math.tanh(gates[2 * G + o]! + r * hn)
      // Every o reads all of h, so h' parks in gates[0..G) (whose r slots are
      // already consumed by this point) and lands in h after the loop.
      gates[o] = (1 - z) * nn + z * h[o]!
    }
    for (let o = 0; o < G; o++) h[o] = gates[o]!
    this.outIn.set(h, 0)
    this.outIn[G] = f0s
    this.outIn[G + 1] = lds
    this.mlp(m.outMlp, this.outIn, this.y)
    matvec(m.harmW, this.y, m.harmB, H, 1 + m.header.nHarmonics, this.harm)
    const amp = expSigmoid(this.harm[0]!)
    const K = m.header.nHarmonics
    const nyq = m.header.sampleRate / 2
    let sum = 0
    for (let k = 0; k < K; k++) {
      const d = (k + 1) * f0Hz < nyq ? expSigmoid(this.harm[1 + k]!) : 0
      this.harmAmps[k] = d
      sum += d
    }
    const scale = amp / (sum + 1e-7)
    for (let k = 0; k < K; k++) this.harmAmps[k] = this.harmAmps[k]! * scale
    matvec(m.noiseW, this.y, m.noiseB, H, m.header.nNoise, this.noiseMags)
    for (let j = 0; j < m.header.nNoise; j++) this.noiseMags[j] = expSigmoid(this.noiseMags[j]!)
  }
}

/* ---------------------------------------------------------------- renderer */

const SINE_N = 8192
const SINE_TABLE = new Float32Array(SINE_N + 1)
for (let i = 0; i <= SINE_N; i++) SINE_TABLE[i] = Math.sin((2 * Math.PI * i) / SINE_N)

/** sin(2*pi*t) for t in [0, 1), table lookup with linear interpolation. */
export function sinTurns(t: number): number {
  const x = t * SINE_N
  const i = x | 0
  const f = x - i
  return SINE_TABLE[i]! * (1 - f) + SINE_TABLE[i + 1]! * f
}

/** One additive sample: sum_k amps[k] * sin(2*pi * frac((k+1) * rev)).
 *  `rev` is the fundamental's phase in revolutions, kept in [0, 1). */
export function ddspHarmSample(rev: number, amps: Float32Array, count: number): number {
  let acc = 0
  for (let k = 0; k < count; k++) {
    const a = amps[k]!
    if (a === 0) continue
    const p = (k + 1) * rev
    acc += a * sinTurns(p - (p | 0))
  }
  return acc
}

/** Spec-exact offline harmonic render (frame i's values at sample i*hop,
 *  linear ramp to frame i+1, last frame holds; rev accumulates BEFORE each
 *  sample is emitted). This is what the golden parity test runs; the kernel
 *  streams the identical per-sample math. */
export function renderHarmonicFrames(
  f0Frames: Float32Array,
  harmAmps: Float32Array[], // per frame, length K each
  sampleRate: number,
  hop: number,
): Float32Array {
  const T = f0Frames.length
  const K = harmAmps[0]?.length ?? 0
  const out = new Float32Array(T * hop)
  const amps = new Float32Array(K)
  let rev = 0
  for (let fr = 0; fr < T; fr++) {
    const f0a = f0Frames[fr]!
    const f0b = fr + 1 < T ? f0Frames[fr + 1]! : f0a
    const aa = harmAmps[fr]!
    const ab = fr + 1 < T ? harmAmps[fr + 1]! : aa
    for (let s = 0; s < hop; s++) {
      const w = s / hop
      const f0 = f0a + (f0b - f0a) * w
      for (let k = 0; k < K; k++) amps[k] = aa[k]! + (ab[k]! - aa[k]!) * w
      rev += f0 / sampleRate
      rev -= rev | 0
      out[fr * hop + s] = ddspHarmSample(rev, amps, K)
    }
  }
  return out
}

/** Windowed linear-phase noise FIR from decoder magnitudes (exported pure for
 *  the frequency-mapping test). `mags` has J bins spanning [0, modelNyquist];
 *  the FIR runs at the ENGINE rate, so bin j of the engine-rate response sits
 *  at magnitude curve position j * rateRatio (engineRate / modelRate) —
 *  without the remap a 22 kHz-trained breath noise would play an octave too
 *  bright on a 48 kHz engine. Linear interpolation between bins; zero above
 *  the model's Nyquist. `cosBasis` is the taps x J table cos(2*pi*t*j/taps);
 *  `out` receives 2*(J-1) taps. */
export function ddspNoiseFir(mags: Float32Array, rateRatio: number, cosBasis: Float32Array, out: Float32Array): void {
  const J = mags.length
  const taps = 2 * (J - 1)
  // resample the magnitude curve onto engine-rate band centers
  const m = SCRATCH_MAGS.length >= J ? SCRATCH_MAGS : new Float32Array(J)
  for (let j = 0; j < J; j++) {
    const x = j * rateRatio
    const i0 = Math.floor(x)
    if (i0 >= J - 1) {
      m[j] = x <= J - 1 ? mags[J - 1]! : 0
    } else {
      const f = x - i0
      m[j] = mags[i0]! * (1 - f) + mags[i0 + 1]! * f
    }
  }
  for (let t = 0; t < taps; t++) {
    // real-input irfft: (1/taps) * (m0 + m_last*cos(pi t) + 2*sum m_j cos)
    let acc = m[0]!
    const row = t * J
    for (let j = 1; j < J - 1; j++) acc += 2 * m[j]! * cosBasis[row + j]!
    acc += m[J - 1]! * cosBasis[row + J - 1]!
    out[t] = acc / taps
  }
  const half = taps / 2 // roll: swap halves (roll by taps/2 either way)
  for (let t = 0; t < half; t++) {
    const a = out[t]!
    out[t] = out[t + half]!
    out[t + half] = a
  }
  for (let t = 0; t < taps; t++) {
    out[t] = out[t]! * (0.5 - 0.5 * Math.cos((2 * Math.PI * t) / (taps - 1)))
  }
}

/** Shared remap scratch (audio-thread no-alloc; 513 covers the format's max
 *  n_noise, and ddspNoiseFir falls back to allocating for anything bigger). */
const SCRATCH_MAGS = new Float32Array(513)

/** cos(2*pi*t*j/taps) basis for ddspNoiseFir, taps x J. */
export function ddspCosBasis(J: number): Float32Array {
  const taps = 2 * (J - 1)
  const basis = new Float32Array(taps * J)
  for (let t = 0; t < taps; t++) {
    for (let j = 0; j < J; j++) basis[t * J + j] = Math.cos((2 * Math.PI * ((t * j) % taps)) / taps)
  }
  return basis
}

/* ------------------------------------------------------------------ kernel */

export interface DdspConfig {
  /** model name resolved against the shared bank each block */
  model?: string
  /** loudness in dB fed to the decoder at full velocity (default -15 — forte
   *  in the calibrated training scale, where 0 dB is a full-scale sine) */
  level?: number
  /** dB of loudness range across velocity 1 -> 0 (default 30) */
  dyn?: number
  /** linear output makeup (default 2): the decoder reproduces the RECORDED
   *  absolute level (a solo instrument peaks ~0.03 full-scale), which is
   *  unmixable next to oscillators at ~1.0. Makeup lives OUTSIDE the model so
   *  the decoder's loudness conditioning stays in its trained scale. */
  gain?: number
  /** loudness attack time constant, seconds (default 0.04) */
  attack?: number
  /** loudness release time constant, seconds (default 0.3) */
  release?: number
  /** dB of extra loudness fed to the decoder for ~80 ms at each retrigger
   *  (default 2.5): the MODEL then produces the bow-change / tongued attack
   *  it learned loud onsets to have, which no amplitude envelope can fake. */
  punch?: number
  /** NOTE-TO-NOTE FLOW (0..2, default 1; 0 = off): scales the performance
   *  conditioning layer that keeps the decoder's inputs inside its TRAINING
   *  distribution at note boundaries. The model learned from crepe curves,
   *  which never step — real playing moves f0 through a ~28 ms S-curve and
   *  dips loudness a few dB at every note change, and THAT trajectory is what
   *  makes the model produce transition sound. Square steps are
   *  out-of-distribution and read as pasted-together notes. Also adds the
   *  within-note settle every sustained instrument has (a couple of dB of
   *  slow decay after the attack). Not portamento: the transition is far
   *  below the ~60 ms where pitch motion reads as a slide. */
  flow?: number
  /** seconds before vibrato reaches full depth after note-on (default 0.6) */
  vibdelay?: number
  /** noise PRNG seed (deterministic renders; default fixed) */
  seed?: number
}

const clampNum = (v: number, lo: number, hi: number): number => (v < lo ? lo : v > hi ? hi : v)

/** The playable instrument. Ports: gate (edge = note), freq (Hz), vel (0..1),
 *  breath (dB offset into the decoder's loudness — the expressive input),
 *  vib (vibrato depth, semitones), vibrate (vibrato rate, Hz), plus the
 *  articulation set: air (noise-vs-harmonic balance, 1 = as trained),
 *  bright (spectral tilt, loudness-preserving, 0 = as trained), scoop
 *  (semitones approached from below at note-on) and fall (semitones dropped
 *  at release). air/bright reshape the decoder's OUTPUTS — the two halves
 *  are separate right up to the sum, which is what makes them cheap.
 *
 *  The decoder is conditioned on (f0, loudness); loudness comes from an
 *  internal attack/release envelope in dB, so dynamics change TIMBRE (that is
 *  the whole point of DDSP), not just gain. Output is harmonic + noise, no
 *  post-VCA. The model resolves by name per block (live loads, like samples);
 *  no model yet = silence. Fully deterministic: seeded noise, no stagger, so
 *  offline renders are reproducible sample-for-sample. */
export class DdspKernel implements Kernel {
  private readonly modelName: string
  private readonly level: number
  private readonly dyn: number
  private readonly gain: number
  private readonly attack: number
  private readonly release: number
  private readonly seed: number

  private model: DdspModel | undefined
  private decoder: DdspDecoder | undefined
  private ampsCur: Float32Array | undefined
  private ampsDelta: Float32Array | undefined
  private fir: Float32Array | undefined
  private firDelta: Float32Array | undefined
  private firNext: Float32Array | undefined
  private noiseRing: Float32Array | undefined
  private firCos: Float32Array | undefined // cached irfft basis for this taps size

  private readonly punch: number
  private readonly vibdelay: number
  private readonly flow: number

  private rev = 0
  private ringPos = 0
  private noiseState: number
  private toTick = 0
  private envDb = -90
  private prevGate = 0
  private noteTime = 0
  /** seconds since the last note boundary (gate edge OR legato pitch change)
   *  and the previous inter-onset interval — the note RATE, which scales
   *  every articulation time constant (a player bows sixteenths with a
   *  faster, lighter stroke than whole notes; fixed constants tuned on slow
   *  phrases made fast passages mushy). */
  private boundTime = 0
  private prevIoi = 0.5
  private vibPhase = 0
  private vibSlow = 0 // slow LFO drifting vibrato rate/depth (humanization)
  private silent = true
  /** pitch articulation: current factor, per-sample multiplier, clamp, mode */
  private artFactor = 1
  private artStep = 1
  private artFloor = 1
  private artMode = 0 // 0 idle, 1 scooping up to 1, 2 falling to artFloor
  private punchDb = 0
  /** note-flow state: the smoothed fundamental the whole voice follows */
  private flowFrom = 0
  private flowTo = 0
  private flowT = 0 // samples into the current transition
  private flowLen = 1 // legacy field kept for reset simplicity
  private flowCur = 0
  private flowCond = 0 // slower fundamental fed to the DECODER only
  private flowCondFrom = 0
  private dipDb = 0 // brief negative loudness at a legato note boundary
  /** micro-intonation: players land a few cents off and correct (tuner-perfect
   *  pitch is the loudest machine tell). Linear-domain deviation, decaying. */
  private intoneDev = 0
  private noteCount = 0 // varies the intonation draw across repeated notes
  /** onset pitch instability: bow bite / breath settling for ~45 ms */
  private wobLeft = 0
  private wobTotal = 1
  private wobLp = 0
  private wobState = 1

  constructor(config: DdspConfig = {}, _ctx?: DspContext) {
    this.modelName = typeof config.model === 'string' ? config.model : ''
    this.level = clampNum(config.level ?? -15, -60, 0)
    this.dyn = clampNum(config.dyn ?? 30, 0, 60)
    this.gain = clampNum(config.gain ?? 2, 0, 64)
    this.attack = clampNum(config.attack ?? 0.04, 0.001, 5)
    this.release = clampNum(config.release ?? 0.3, 0.005, 10)
    this.punch = clampNum(config.punch ?? 2.5, 0, 12)
    this.vibdelay = clampNum(config.vibdelay ?? 0.6, 0, 5)
    this.flow = clampNum(config.flow ?? 1, 0, 2)
    this.seed = ((config.seed ?? 0x2f6e2b1) >>> 0) || 1
    this.noiseState = this.seed
  }

  reset(): void {
    this.decoder?.reset()
    this.ampsCur?.fill(0)
    this.ampsDelta?.fill(0)
    this.fir?.fill(0)
    this.firDelta?.fill(0)
    this.noiseRing?.fill(0)
    this.rev = 0
    this.ringPos = 0
    this.noiseState = this.seed
    this.toTick = 0
    this.envDb = -90
    this.prevGate = 0
    this.noteTime = 0
    this.boundTime = 0
    this.prevIoi = 0.5
    this.vibPhase = 0
    this.vibSlow = 0
    this.silent = true
    this.artFactor = 1
    this.artStep = 1
    this.artFloor = 1
    this.artMode = 0
    this.punchDb = 0
    this.flowFrom = 0
    this.flowTo = 0
    this.flowT = 0
    this.flowLen = 1
    this.flowCur = 0
    this.flowCond = 0
    this.flowCondFrom = 0
    this.dipDb = 0
    this.intoneDev = 0
    this.noteCount = 0
    this.wobLeft = 0
    this.wobTotal = 1
    this.wobLp = 0
    this.wobState = 1
  }

  /** The decoder's current loudness conditioning in dB (the articulation
   *  envelope). For tests and meters — the fixture models' random weights
   *  make output amplitude non-monotonic in loudness, so envelope behavior
   *  is asserted here, not through the audio. */
  currentLoudness(): number {
    return this.envDb
  }

  /** The fundamental the voice is following right now (post flow, pre
   *  vibrato/articulation), in Hz. For tests and meters: spectral windows
   *  cannot resolve a 30 ms transition (Δf·Δt), but this can. */
  currentF0(): number {
    return this.flowCur
  }

  /** Start-of-note humanization: draw this note's intonation offset (±5
   *  cents, correcting over ~0.45 s) and arm the onset pitch wobble (~45 ms
   *  of settling). Deterministic — everything derives from noteHash01. */
  private newNoteHumanization(f: number, sr: number): void {
    this.noteCount++
    const h = this.noteHash01(f)
    this.intoneDev = (h * 2 - 1) * 5 * this.flow * (Math.LN2 / 1200) // ±5 cents
    this.wobTotal = Math.max(1, Math.round(0.045 * sr))
    this.wobLeft = this.wobTotal
    this.wobLp = 0
    this.wobState = ((h * 0xffffffff) >>> 0) || 1
  }

  /** Deterministic per-note draw in [0, 1): hashes the note, the running note
   *  count (so a repeated note re-draws) and the seed. */
  private noteHash01(f: number): number {
    let h = ((Math.abs(f * 128) | 0) + Math.imul(this.noteCount, 0x9e3779b1)) ^ this.seed
    h = Math.imul(h ^ (h >>> 16), 0x45d9f3b)
    h = Math.imul(h ^ (h >>> 13), 0x45d9f3b)
    return ((h ^ (h >>> 16)) >>> 0) / 0x100000000
  }

  /** (Re)bind to a model. The ONE place this kernel allocates outside the
   *  constructor: models arrive over the wire after compile (same lifecycle
   *  as samples), so per-voice state can only be sized once the model exists.
   *  Happens once per model load, a few KB, while the voice is silent. */
  private bind(model: DdspModel): void {
    this.model = model
    this.decoder = new DdspDecoder(model)
    const K = model.header.nHarmonics
    const taps = 2 * (model.header.nNoise - 1)
    this.ampsCur = new Float32Array(K)
    this.ampsDelta = new Float32Array(K)
    this.fir = new Float32Array(taps)
    this.firDelta = new Float32Array(taps)
    this.firNext = new Float32Array(taps)
    this.noiseRing = new Float32Array(taps) // power of two (parse enforces)
    // irfft cos basis, computed once per bind off the hot path
    this.firCos = ddspCosBasis(model.header.nNoise)
    this.rev = 0
    this.ringPos = 0
    this.toTick = 0
  }

  /** Windowed linear-phase FIR from magnitudes: irfft, roll by taps/2, Hann.
   *  Matches ddsp/synth.py::noise_fir when the rates agree; `rateRatio`
   *  (engine rate / model rate) keeps the noise BANDS at their trained
   *  absolute frequencies when they differ. Writes into firNext. */
  private buildFir(mags: Float32Array, rateRatio: number): void {
    ddspNoiseFir(mags, rateRatio, this.firCos!, this.firNext!)
  }

  process(n: number, inputs: Record<string, Float32Array>, out: Float32Array, ctx: DspContext): void {
    const model = ctx.ddsp?.get(this.modelName) as DdspModel | undefined
    if (!model) {
      out.fill(0, 0, n)
      return
    }
    if (model !== this.model) this.bind(model)
    const gate = inputs['gate']!
    const freq = inputs['freq']!
    const vel = inputs['vel']!
    const breath = inputs['breath']!
    const vib = inputs['vib']!
    const vibrate = inputs['vibrate']!
    const air = inputs['air']!
    const bright = inputs['bright']!
    const scoop = inputs['scoop']!
    const fall = inputs['fall']!
    const sr = ctx.sampleRate
    const hop = Math.max(1, Math.round((model.header.hop / model.header.sampleRate) * sr))
    const K = model.header.nHarmonics
    const taps = this.fir!.length
    const ringMask = taps - 1
    const decoder = this.decoder!
    const ampsCur = this.ampsCur!
    const ampsDelta = this.ampsDelta!
    const fir = this.fir!
    const firDelta = this.firDelta!
    const firNext = this.firNext!
    const ring = this.noiseRing!
    const engNyq = sr / 2
    const hopSec = hop / sr
    const rateRatio = sr / model.header.sampleRate
    // note-to-note flow: ~28 ms S-curve pitch transitions, a few dB loudness
    // dip at legato boundaries, slow within-note settle (see DdspConfig.flow)
    const flowOn = this.flow > 0
    const renderSamples = Math.max(1, Math.round(0.008 * sr))
    const condSamples = Math.max(1, Math.round(0.02 * sr))
    // dip recovery: 50 ms on slow phrases, ~a fifth of the note on fast ones
    const dipDecayFor = (ioi: number): number => Math.exp(-1 / (Math.min(0.05, ioi / 5) * sr))
    const intoneDecay = Math.exp(-1 / (0.45 * sr)) // players correct over ~half a second
    const settleDb = 2.5 * this.flow
    // ONSET TEXTURE: a bowed/blown attack is not a quiet sustain — it is
    // noise-dominated (bow scratch, breath chiff) with harmonics blooming
    // from the bottom up. The decoder cannot know a frame is an onset
    // (loudness-only conditioning), so the articulation layer reshapes its
    // outputs: noise boosted and top harmonics held back, both decaying over
    // the first tens of ms. The noise SPECTRUM stays the model's own, so a
    // cello scratches like a cello and a flute chiffs like a flute.
    const onsetAirTau = 0.035
    const onsetBloomTau = 0.06
    const outGain = this.gain * (model.header.outNorm || 1) // || guards hand-built model objects
    let noiseX = this.noiseState

    for (let i = 0; i < n; i++) {
      const g = gate[i]!
      const rising = g > 0 && this.prevGate <= 0
      const falling = g <= 0 && this.prevGate > 0
      this.prevGate = g
      if (rising) {
        this.noteTime = 0
        this.prevIoi = clampNum(this.boundTime, 0.03, 2)
        this.boundTime = 0
        this.punchDb = this.punch // decoder-side attack accent, decays per tick
        const s = clampNum(scoop[i]!, 0, 12)
        if (s > 0) {
          // approach from s semitones below, gliding up over ~80 ms — one pow
          // here, then a single multiply per sample
          this.artFactor = Math.pow(2, -s / 12)
          this.artStep = Math.pow(1 / this.artFactor, 1 / (0.08 * sr))
          this.artMode = 1
        }
        // Waking from silence, stagger this voice's decoder tick by a hash of
        // the NOTE (deterministic — it depends only on inputs, so offline
        // renders stay reproducible), so an 8-voice chord doesn't run all its
        // GRUs in one 128-frame quantum. Costs up to one hop (~10 ms) of
        // onset latency, well under the loudness envelope's attack.
        if (this.silent) {
          let hsh = (Math.abs(freq[i]! * 256) | 0) ^ this.seed
          hsh = Math.imul(hsh ^ (hsh >>> 15), 0x2c1b3c6d)
          hsh = (hsh ^ (hsh >>> 12)) >>> 0
          this.toTick = hsh % hop
        }
      } else if (falling) {
        const f = clampNum(fall[i]!, 0, 12)
        if (f > 0) {
          // drop up to f semitones over ~120 ms while the release rings out
          this.artFloor = Math.pow(2, -f / 12) * this.artFactor
          this.artStep = Math.pow(2, -f / 12 / (0.12 * sr))
          this.artMode = 2
        }
      }
      if (this.silent && g <= 0 && this.toTick > 0) {
        // Fully released and idle: silence without decoder or noise work.
        out[i] = 0
        this.toTick--
        continue
      }
      // note-to-note flow, TWO tracks with different jobs:
      //  - the RENDERED pitch (flowCur) snaps in ~8 ms — a real finger change
      //    is near-instant, and anything slower reads as portamento smear
      //    (it did, on fast passages, at the old 28-56 ms)
      //  - the DECODER's conditioning (flowCond) takes ~20 ms, matching what
      //    crepe extraction actually shows at note changes (1-2 frames), so
      //    the model stays in-distribution and produces the boundary sound
      // A legato jump (no gate edge) also dips the decoder's loudness — the
      // other half of the boundary signal it learned.
      const fRawIn = freq[i]!
      const fIn = Number.isFinite(fRawIn) && fRawIn > 0 ? fRawIn : 0
      if (!flowOn || fIn === 0) {
        this.flowCur = fIn
        this.flowCond = fIn
        this.flowTo = fIn
      } else if (this.flowCur === 0 || rising) {
        // from silence (or a fresh attack): start AT the note, no transition
        this.flowCur = fIn
        this.flowCond = fIn
        this.flowFrom = fIn
        this.flowTo = fIn
        this.flowT = 1 << 30
      } else if (Math.abs(fIn - this.flowTo) > this.flowTo * 0.015) {
        this.flowFrom = this.flowCur // retarget from wherever we are now
        this.flowCondFrom = this.flowCond
        this.flowTo = fIn
        this.flowT = 0
        this.prevIoi = clampNum(this.boundTime, 0.03, 2)
        this.boundTime = 0
        // legato boundary dip: gentler and quicker when notes come fast, or
        // sixteenth runs flutter instead of flowing
        if (g > 0) this.dipDb = -3.5 * this.flow * clampNum(this.prevIoi / 0.15, 0.5, 1)
        this.newNoteHumanization(fIn, sr)
      }
      if (this.flowT < condSamples) {
        this.flowT++
        if (this.flowT >= renderSamples) {
          this.flowCur = this.flowTo
        } else {
          const t = this.flowT / renderSamples
          const s = t * t * (3 - 2 * t)
          this.flowCur = this.flowFrom + (this.flowTo - this.flowFrom) * s
        }
        const tc = Math.min(1, this.flowT / condSamples)
        const sc = tc * tc * (3 - 2 * tc)
        this.flowCond = this.flowCondFrom + (this.flowTo - this.flowCondFrom) * sc
      } else {
        this.flowCur = this.flowTo
        this.flowCond = this.flowTo
      }
      this.dipDb *= dipDecayFor(this.prevIoi)
      // micro-intonation correction + onset wobble (see field docs)
      this.intoneDev *= intoneDecay
      let humanF = 1 + this.intoneDev
      if (this.wobLeft > 0) {
        this.wobLeft--
        let x = this.wobState
        x ^= x << 13
        x ^= x >>> 17
        x ^= x << 5
        x >>>= 0
        this.wobState = x
        this.wobLp += (x / 0x80000000 - 1 - this.wobLp) * 0.02
        const fade = this.wobLeft / this.wobTotal
        humanF += this.wobLp * fade * 0.0035 * this.flow // ~±6 cents at onset
      }
      // vibrato LFO advances exactly once per audible sample; the same factor
      // feeds the decoder's f0 (at ticks) and the oscillator bank. Pitch
      // articulation (scoop/fall) rides along multiplicatively.
      if (this.artMode === 1) {
        this.artFactor *= this.artStep
        if (this.artFactor >= 1) {
          this.artFactor = 1
          this.artMode = 0
        }
      } else if (this.artMode === 2) {
        this.artFactor *= this.artStep
        if (this.artFactor <= this.artFloor) {
          this.artFactor = this.artFloor
          this.artMode = 0
        }
      }
      const vibNow = this.vibFactor(vib[i]!, vibrate[i]!, sr, flowOn) * this.artFactor * humanF
      if (this.toTick <= 0) {
        this.toTick = hop
        // loudness envelope (frame rate, dB domain); punch rides the target
        // for the first few frames of a note so the DECODER plays the accent
        const v = clampNum(vel[i]!, 0, 1)
        const target =
          g > 0 ? this.level - (1 - v) * this.dyn + clampNum(breath[i]!, -24, 24) + this.punchDb : -90
        // fast notes SPEAK: attack shortens to ~a sixth of the note, release
        // to ~a third (floored so phrase endings still ring), punch decays
        // within the note instead of blurring across it
        const atkTau = clampNum(Math.min(this.attack, this.prevIoi / 6), 0.006, this.attack)
        const relTau = clampNum(Math.min(this.release, Math.max(0.08, this.prevIoi / 3)), 0.02, this.release)
        this.punchDb *= Math.exp(-hopSec / Math.min(0.035, this.prevIoi / 5))
        this.envDb += (target - this.envDb) * (1 - Math.exp(-hopSec / (g > 0 ? atkTau : relTau)))
        this.silent = g <= 0 && this.envDb <= -85
        if (!this.silent) {
          const f0 = (this.flowCond > 0 ? this.flowCond : 1e-5) * vibNow
          // dip marks the note boundary; settle is the slow post-attack decay
          // every sustained instrument has — both keep the decoder's loudness
          // trajectory looking like the performances it learned from
          const settle = -settleDb * (1 - Math.exp(-this.noteTime / 1.2))
          decoder.step(f0, this.envDb + this.dipDb + settle)
          // bright: loudness-preserving spectral tilt of the harmonic set,
          // plus the onset bloom (top partials arrive late on real attacks)
          const onsetT = this.noteTime
          const bloom = this.flow * 0.45 * Math.exp(-onsetT / onsetBloomTau)
          const b = clampNum(bright[i]!, -3, 3) - bloom
          if (b !== 0) {
            let sum0 = 0
            let sumW = 0
            for (let k = 0; k < K; k++) {
              const a = decoder.harmAmps[k]!
              const w = Math.pow(k + 1, b)
              sum0 += a
              sumW += a * w
              decoder.harmAmps[k] = a * w
            }
            if (sumW > 1e-12) {
              const norm = sum0 / sumW
              for (let k = 0; k < K; k++) decoder.harmAmps[k] = decoder.harmAmps[k]! * norm
            }
          }
          for (let k = 0; k < K; k++) {
            const target2 = (k + 1) * f0 < engNyq ? decoder.harmAmps[k]! : 0
            ampsDelta[k] = (target2 - ampsCur[k]!) / hop
          }
          this.buildFir(decoder.noiseMags, rateRatio)
          // air: scale the noise half against the harmonics (1 = as trained),
          // times the floor gate: below ~-45 dB conditioning a real
          // instrument is silent, but the noise head reproduces the
          // RECORDING's room floor there — every release would hiss.
          const floorGate = clampNum((this.envDb + 75) / 30, 0, 1)
          const scratch = 1 + this.flow * 1.4 * Math.exp(-onsetT / onsetAirTau)
          const airNow = clampNum(air[i]!, 0, 4) * floorGate * scratch
          if (airNow !== 1) {
            for (let t = 0; t < taps; t++) firNext[t] = firNext[t]! * airNow
          }
          for (let t = 0; t < taps; t++) firDelta[t] = (firNext[t]! - fir[t]!) / hop
        } else {
          ampsCur.fill(0)
          ampsDelta.fill(0)
          fir.fill(0)
          firDelta.fill(0)
        }
      }
      this.toTick--
      if (this.silent) {
        out[i] = 0
        continue
      }
      // per-sample: ramp amps + FIR toward the current frame's targets
      for (let k = 0; k < K; k++) ampsCur[k] = ampsCur[k]! + ampsDelta[k]!
      for (let t = 0; t < taps; t++) fir[t] = fir[t]! + firDelta[t]!
      const fSyn = this.flowCur * vibNow
      this.rev += fSyn / sr
      this.rev -= this.rev | 0
      let acc = ddspHarmSample(this.rev, ampsCur, K)
      // filtered noise: xorshift white noise through the interpolated FIR
      noiseX ^= noiseX << 13
      noiseX ^= noiseX >>> 17
      noiseX ^= noiseX << 5
      noiseX >>>= 0
      ring[this.ringPos] = noiseX / 0x80000000 - 1
      for (let t = 0; t < taps; t++) acc += fir[t]! * ring[(this.ringPos - t + taps) & ringMask]!
      this.ringPos = (this.ringPos + 1) & ringMask
      out[i] = acc * outGain
      this.noteTime += 1 / sr
      this.boundTime += 1 / sr
    }
    this.noiseState = noiseX
    this.rev = flush(this.rev)
    if (!Number.isFinite(this.envDb)) this.envDb = -90
  }

  /** Advances the vibrato LFO one sample and returns the pitch factor.
   *  Depth ramps in over `vibdelay` seconds after note-on (real players delay
   *  vibrato), and a slow deterministic LFO drifts rate and depth a few
   *  percent — a metronomic vibrato is the tell of a synthetic player. */
  private vibFactor(depth: number, rate: number, sr: number, conditioned: boolean): number {
    const d = clampNum(depth, 0, 2)
    const r = clampNum(rate, 0, 20)
    this.vibSlow += 0.31 / sr
    this.vibSlow -= this.vibSlow | 0
    const drift = sinTurns(this.vibSlow)
    this.vibPhase += (r * (1 + 0.05 * drift)) / sr
    this.vibPhase -= this.vibPhase | 0
    if (d === 0) return 1
    const ramp = this.noteTime > this.vibdelay ? 1 : this.vibdelay <= 0 ? 1 : this.noteTime / this.vibdelay
    let dHuman = d * (1 + 0.07 * sinTurns((this.vibSlow * 0.618 + 0.37) % 1))
    // players vibrate WITH the sound: quiet playing gets shallow vibrato
    if (conditioned) dHuman *= clampNum((this.envDb + 55) / 35, 0.25, 1.15)
    // 2^(x/12) ~= 1 + x * ln2/12 for the small x vibrato uses
    return 1 + dHuman * ramp * sinTurns(this.vibPhase) * (Math.LN2 / 12)
  }
}
